### PR TITLE
Fixing exercises deletion - Fixes #1063

### LINKED ISSUE #1063: Exercises that were deleted in bibliotheca are not being removed from laboratory

### PR DESCRIPTION
**Pull request by rodri042**
Fixes #1063

### CODE REVIEW

File: spec/models/guide_import_spec.rb [hunk 1]
```diff
@@ -115,7 +115,7 @@
       end
 
       describe 'it is removed from the guide' do
-        it { expect(guide.exercises.count).to eq 6 }
```
Comment (rodri042) [inline spec/models/guide_import_spec.rb]: This assert was wrong because initially the guide has 6 exercises (https://github.com/mumuki/mumuki-laboratory/blob/b879100110b943a17d82839d8740d065cde9722e/spec/models/guide_import_spec.rb#L75) and after importing and applying the json (https://github.com/mumuki/mumuki-laboratory/blob/b879100110b943a17d82839d8740d065cde9722e/spec/models/guide_import_spec.rb#L19) it should have 5 exercises
