### PR TITLE
slice for attribute names before updates

### LINKED ISSUE #1169: imports should rely on a whitelist rather than a blacklist to prevent import fails when another app changes

### PR DESCRIPTION
**Pull request by julian-berbel**
Fixes #1169.

This is a pretty lazy implementation tbh.

Rather than explicitly writing the list I opted for using the attribute_names to avoid having to update the list every time the model changes.

I still needed to except some fields because both laboratory and bibliotheca export them but with different meanings.

### CODE REVIEW

File: app/models/guide.rb [hunk 1]
```diff
@@ -58,7 +58,7 @@ def done_for?(user)
   end
 
   def import_from_json!(json)
-    self.assign_attributes json.except('exercises', 'language', 'id_format', 'id', 'teacher_info', 'collaborators', 'private')
+    self.assign_attributes json.slice(*attribute_names).except 'id'
```
Comment (flbulgarelli) [inline app/models/guide.rb]: Perhaps we could put this idiom in the `ApplicationRecord` class, so that we can do `self.slice_attribute_names(a_hash)` or `self.ẁhitelist_attributes(a_hash)`, or `self.ẁhitelist_attributes(a_hash, except: %w(type id))`
