### PR TITLE
Fix mobile profile buttons

### LINKED ISSUE #1470: Improve buttons positioning for mobile in profile layouts
Currently it looks ok, but the buttons are too big and the header positioning is also weird.
We could try downsizing that button, moving it a row below or replacing it for an icon

### PR DESCRIPTION
**Pull request by felipecalvo**
Closes #1470

I moved the buttons to the bottom. The edit profile button didn't look good between the name and the avatar, and I tried between the avatar and the profile fields too and it didn't look good either. An edit icon next to the name is another option, but even then there might be long names + small screens where it'll still look wrong.

For the cancel / save edition buttons it makes the most sense to have them at the bottom, too. Scroll to edit, keep scrolling and save. On mobile, they look out of place at the top, and it makes you scroll down to edit then up to save.

I'm keeping stuff as it is on larger screens, of course.

____

This is the edit profile view on a very thin iPhone 5

_____

This is the profile view on a wider phone

### CODE REVIEW

File: app/helpers/profile_helper.rb [hunk 1]
```diff
@@ -2,4 +2,12 @@ module ProfileHelper
   def edit_profile_button
     link_to t(:edit_profile), edit_user_path, class: 'btn btn-success'
   end
+
+  def cancel_edit_profile_button
+    link_to t(:cancel), :back, class: 'btn btn-default' if current_user.profile_completed?
+  end
```
Comment (felipecalvo) [inline app/helpers/profile_helper.rb:8]: Would changing this to

```suggestion
  def cancel_edit_profile_button
    link_to t(:cancel), :user_path, class: 'btn btn-default' if current_user.profile_completed?
  end
```
fix this very small https://github.com/mumuki/mumuki-laboratory/issues/1483 issue?

Or would it break some redirection stuff or use case I'm unaware of?

**Comment by luchotc** [comment]
I've just tested it locally to see it in action and I love it. The only thing I'm not sure is the fact that in one scenario we are showing it a the top and in the other at the bottom. But I definitely agree with you that in mobile the buttons should be at the bottom. 
I'm more and more convinced that the cancel button should be a back arrow instead of the hamburger, at least when you are coming from the read_only profile.
But this is a huge improvement as it is, so let's merge it!
