### PR TITLE
Placeholder for broken profile images - Fixes #1123

### LINKED ISSUE #1123: No se muestra de forma "linda" el logo del perfil
image

Cuando no existe la url de la imagen del usuario, deberiamos mostrar como alternativa su nombre.

### PR DESCRIPTION
**Pull request by rodri042**
Fixes #1123

screenshot5

### CODE REVIEW

File: app/helpers/progress_helper.rb [hunk 1]
```diff
@@ -1,18 +1,19 @@
...
-      :start_lesson
-    end
+    key_or_default stats, :started?, :continue_lesson, :start_lesson
   end
 
-  #FIXME refactorme: similar methods
   def book_practice_key_for(student)
-    if student.try(:last_exercise)
-      :continue_practicing
+    key_or_default student, :last_exercise, :continue_practicing, :start_practicing
```
Comment (flbulgarelli) [inline app/helpers/progress_helper.rb]: I think this is better than what we had, but I still don't like having 4 parameters.  

However, I think that the whole navigation code should be refactored, since it is buggy and not easy to modify. See: 

* https://github.com/mumuki/mumuki-laboratory/issues/1105
* https://github.com/mumuki/mumuki-laboratory/issues/855
