### PR TITLE
Fix codemirror mobile

### LINKED ISSUE #823: Code Mirror Editor is still troublesome in some mobile devices
* The editor's placeholder doesn't hide after a first complete token is entered
* End parenthesis are sometimes not rendered
* Deleting text will sometimes led to text duplication
* Text is sometimes entered by column instead of by row

### PR DESCRIPTION
**Pull request by fedescarpa**
Fixes #823

### CODE REVIEW

File: app/assets/javascripts/application.js [hunk 1]
```diff
@@ -16,22 +16,6 @@
 //= require jquery
 //= require jquery_ujs
 //= require bootstrap
-//= require codemirror
-//= require codemirror/modes/ruby
-//= require codemirror/modes/haskell
```
Comment (flbulgarelli) [inline app/assets/javascripts/application.js]: Could we add those js files in the vendor directory as minified js's? 

Otherwise, we are adding a lot of overhead to laboratory's minifier during build, making deployments slower.

Also, code climate is going to detect hundreds of errors which we shoudn't care about.

File: app/assets/javascripts/application/codemirror-modes/alias-modes.js [hunk 2]
```diff
@@ -0,0 +1,20 @@
...
+    CodeMirror.defineMIME(alias, CodeMirror.mimeModes[current]);
+  }
+
+  CodeMirrorAlias('c', 'text/x-csrc');
+  CodeMirrorAlias('cpp', 'text/x-c++src');
+  CodeMirrorAlias('c_cpp', 'text/x-c++src');
+
+  CodeMirrorAlias("html", "text/html");
+
+  CodeMirrorAlias('java', 'text/x-java');
```
Comment (flbulgarelli) [inline app/assets/javascripts/application/codemirror-modes/alias-modes.js]: Nice!

File: app/assets/javascripts/application/codemirror-modes/alias-modes.js [hunk 3]
```diff
@@ -0,0 +1,20 @@
...
+
+  CodeMirrorAlias('sql', 'text/x-sql');
+
+  CodeMirrorAlias('sh', 'text/x-sh');
+  CodeMirrorAlias('bash', 'text/x-sh');
```
Comment (flbulgarelli) [inline app/assets/javascripts/application/codemirror-modes/alias-modes.js]: I don't find many missing modes here, should we add them?

* Prolog
* Haskell
* JavaScript
* Ruby
* Gobstones
* Wollok
* ASM/QSIM/Assembler
* Python
* Elixir

See http://runners.mumuki.io/runners

File: app/views/layouts/application.html.erb [hunk 4]
```diff
@@ -6,6 +6,14 @@
   <link rel="icon" type="image/x-icon" href="/favicon.ico">
   <link rel="stylesheet" type="text/css" href="<%= theme_stylesheet_url %>">
 
+  <% codemirror_assets_css.each do |it| %>
+      <link rel="stylesheet" type="text/css" href="<%= it %>">
+  <% end %>
+
+  <% codemirror_assets_js.each do |it| %>
```
Comment (flbulgarelli) [inline app/views/layouts/application.html.erb]: I think that if we place those assets on vendor folder, this is not necessary. 

Moreover, I am not sure assets included this way will be minified :scream:
